type Movies {
  title: String
  overview: String
  poster_path: String
  popularity: String
  tag: String
  status: String
}

type Series {
  title: String
  overview: String
  poster_path: String
  popularity: String
  tag: String
  status: String
}

type Orches {
  Movies: [Movies]
  Series: [Series]
}

type Query {
  fetchData: Orches
}

type Mutation {
  addMovie(movie: MovieData): Movies
}

input MovieData {
  title: String!
  overview: String!
  poster_path: String
  popularity: String
  tag: String
  status: String
}
